#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Dec 04, 2018 06:13:36 PM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family ÐÂËÎÌå -size 11 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 368x359+100+84
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1050
    wm minsize $top 176 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Start - PyChat"
    vTcl:DefineAlias "$top" "ToplevelStart" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Server IP:} 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "ToplevelStart" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Port: 
    vTcl:DefineAlias "$top.lab49" "Label2" vTcl:WidgetProc "ToplevelStart" 1
    entry $top.ent50 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable ui_server_ip 
    vTcl:DefineAlias "$top.ent50" "ent_server_ip" vTcl:WidgetProc "ToplevelStart" 1
    entry $top.ent51 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable ui_server_port 
    vTcl:DefineAlias "$top.ent51" "ent_server_port" vTcl:WidgetProc "ToplevelStart" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo45 \
        -width 354 -height 256 -takefocus {} 
    vTcl:DefineAlias "$top.tNo45" "TNotebook1" vTcl:WidgetProc "ToplevelStart" 1
    frame $top.tNo45.t0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo45.t0" "TNotebook1_t0" vTcl:WidgetProc "ToplevelStart" 1
    $top.tNo45 add $top.tNo45.t0 \
        -padding 0 -sticky nsew -state normal -text Login -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo45.t0
    label $site_4_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Username: 
    vTcl:DefineAlias "$site_4_0.lab52" "Label3" vTcl:WidgetProc "ToplevelStart" 1
    label $site_4_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Password: 
    vTcl:DefineAlias "$site_4_0.lab53" "Label4" vTcl:WidgetProc "ToplevelStart" 1
    entry $site_4_0.ent54 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable ui_login_usr 
    vTcl:DefineAlias "$site_4_0.ent54" "ent_login_usr" vTcl:WidgetProc "ToplevelStart" 1
    entry $site_4_0.ent55 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -show * -textvariable ui_login_pwd 
    vTcl:DefineAlias "$site_4_0.ent55" "ent_login_pwd" vTcl:WidgetProc "ToplevelStart" 1
    button $site_4_0.but57 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command btnLogin -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Login 
    vTcl:DefineAlias "$site_4_0.but57" "Button1" vTcl:WidgetProc "ToplevelStart" 1
    button $site_4_0.but43 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -state disabled -text {Face Login} 
    vTcl:DefineAlias "$site_4_0.but43" "Button4" vTcl:WidgetProc "ToplevelStart" 1
    place $site_4_0.lab52 \
        -in $site_4_0 -x 30 -y 20 -anchor nw -bordermode ignore 
    place $site_4_0.lab53 \
        -in $site_4_0 -x 32 -y 60 -width 86 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent54 \
        -in $site_4_0 -x 130 -y 20 -width 194 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent55 \
        -in $site_4_0 -x 130 -y 60 -width 194 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but57 \
        -in $site_4_0 -x 250 -y 120 -width 88 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but43 \
        -in $site_4_0 -x 10 -y 120 -width 99 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo45.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo45.t1" "TNotebook1_t1" vTcl:WidgetProc "ToplevelStart" 1
    $top.tNo45 add $top.tNo45.t1 \
        -padding 0 -sticky nsew -state normal -text Register -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo45.t1
    label $site_4_1.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Username: 
    vTcl:DefineAlias "$site_4_1.lab58" "Label5" vTcl:WidgetProc "ToplevelStart" 1
    label $site_4_1.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Password: 
    vTcl:DefineAlias "$site_4_1.lab59" "Label6" vTcl:WidgetProc "ToplevelStart" 1
    label $site_4_1.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Confirm: 
    vTcl:DefineAlias "$site_4_1.lab60" "Label7" vTcl:WidgetProc "ToplevelStart" 1
    entry $site_4_1.ent61 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable ui_reg_usr 
    vTcl:DefineAlias "$site_4_1.ent61" "ent_reg_usr" vTcl:WidgetProc "ToplevelStart" 1
    entry $site_4_1.ent62 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -show * -textvariable ui_reg_pwd 
    vTcl:DefineAlias "$site_4_1.ent62" "ent_reg_pwd" vTcl:WidgetProc "ToplevelStart" 1
    entry $site_4_1.ent63 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -show * -textvariable ui_reg_confirm 
    vTcl:DefineAlias "$site_4_1.ent63" "ent_reg_confirm" vTcl:WidgetProc "ToplevelStart" 1
    button $site_4_1.but64 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command btnRegister \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Register 
    vTcl:DefineAlias "$site_4_1.but64" "Button2" vTcl:WidgetProc "ToplevelStart" 1
    button $site_4_1.but44 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -state disabled -text {Add Face} 
    vTcl:DefineAlias "$site_4_1.but44" "Button5" vTcl:WidgetProc "ToplevelStart" 1
    place $site_4_1.lab58 \
        -in $site_4_1 -x 30 -y 20 -anchor nw -bordermode ignore 
    place $site_4_1.lab59 \
        -in $site_4_1 -x 32 -y 60 -width 86 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab60 \
        -in $site_4_1 -x 43 -y 100 -width 74 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent61 \
        -in $site_4_1 -x 130 -y 20 -width 194 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent62 \
        -in $site_4_1 -x 130 -y 60 -width 194 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent63 \
        -in $site_4_1 -x 130 -y 100 -width 194 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but64 \
        -in $site_4_1 -x 250 -y 140 -width 88 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but44 \
        -in $site_4_1 -x 10 -y 140 -width 78 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo45.t2 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo45.t2" "TNotebook1_t2" vTcl:WidgetProc "ToplevelStart" 1
    $top.tNo45 add $top.tNo45.t2 \
        -padding 0 -sticky nsew -state normal -text {Change Password} \
        -image {} -compound none -underline -1 
    set site_4_2  $top.tNo45.t2
    label $site_4_2.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Username: 
    vTcl:DefineAlias "$site_4_2.lab68" "Label8" vTcl:WidgetProc "ToplevelStart" 1
    label $site_4_2.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text {Old pwd:} 
    vTcl:DefineAlias "$site_4_2.lab69" "Label9" vTcl:WidgetProc "ToplevelStart" 1
    label $site_4_2.lab70 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text {New pwd:} 
    vTcl:DefineAlias "$site_4_2.lab70" "Label10" vTcl:WidgetProc "ToplevelStart" 1
    label $site_4_2.lab71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Confirm: 
    vTcl:DefineAlias "$site_4_2.lab71" "Label11" vTcl:WidgetProc "ToplevelStart" 1
    entry $site_4_2.ent75 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable ui_chg_usr 
    vTcl:DefineAlias "$site_4_2.ent75" "ent_chg_usr" vTcl:WidgetProc "ToplevelStart" 1
    entry $site_4_2.ent76 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -show * -textvariable ui_chg_oldpwd 
    vTcl:DefineAlias "$site_4_2.ent76" "ent_reg_oldpwd" vTcl:WidgetProc "ToplevelStart" 1
    entry $site_4_2.ent77 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -show * -textvariable ui_chg_newpwd 
    vTcl:DefineAlias "$site_4_2.ent77" "ent_chg_newpwd" vTcl:WidgetProc "ToplevelStart" 1
    entry $site_4_2.ent78 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -show * -textvariable ui_chg_confirm 
    vTcl:DefineAlias "$site_4_2.ent78" "ent_chg_confirm" vTcl:WidgetProc "ToplevelStart" 1
    button $site_4_2.but79 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command btnChgpwd \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Apply -width 98 
    vTcl:DefineAlias "$site_4_2.but79" "Button3" vTcl:WidgetProc "ToplevelStart" 1
    place $site_4_2.lab68 \
        -in $site_4_2 -x 30 -y 20 -anchor nw -bordermode ignore 
    place $site_4_2.lab69 \
        -in $site_4_2 -x 39 -y 60 -width 79 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab70 \
        -in $site_4_2 -x 32 -y 100 -width 85 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab71 \
        -in $site_4_2 -x 42 -y 140 -width 74 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_2.ent75 \
        -in $site_4_2 -x 130 -y 20 -width 194 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent76 \
        -in $site_4_2 -x 130 -y 60 -width 194 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent77 \
        -in $site_4_2 -x 130 -y 100 -width 194 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent78 \
        -in $site_4_2 -x 130 -y 140 -width 194 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but79 \
        -in $site_4_2 -x 250 -y 180 -width 98 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 30 -y 16 -width 79 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.lab49 \
        -in $top -x 65 -y 56 -width 43 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.ent50 \
        -in $top -x 120 -y 20 -width 204 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 120 -y 62 -width 204 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tNo45 \
        -in $top -x 10 -y 100 -width 354 -height 256 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

